name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.18]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod download
      - run: go test -bench=. -benchmem -v .
      - run: go test -bench=. -benchmem -v . -race
      - name: Run cover tests
        run: go test -covermode atomic -coverprofile=covprofile -v .
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github